name: cucumber_dart
description: A simple command-line application.
version: 1.0.0
# homepage: https://www.example.com
publish_to: 'none'

environment:
  sdk: '>=2.14.2 <3.0.0'

dependencies:
  path: ^1.8.0
  yaml: ^3.1.0
  gherkin:
    path: ../cucumber-common/gherkin/dart
    #git:
      #url: https://github.com/cucumber/common.git
      #path: gherkin/dart

dev_dependencies:
  lints: ^1.0.1
  test: any

cucumber:
  features:
    - test/features/calc.feature

test:
  assets:
    - test/json/user.json
